services:
  postgres:
    image: postgres:17
    container_name: wongnok-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pe@devp00l
    ports:
      - "5432:5432"
    volumes:
      - wongnok-pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.10-alpine
    container_name: wongnok-redis
    restart: always
    ports:
      - "6380:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    container_name: wongnok-keycloak
    restart: always
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8081:8080"
    volumes:
      - wongnok-keycloak-data:/opt/keycloak/data

volumes:
  wongnok-pgdata:
  wongnok-keycloak-data:
